### PR TITLE
fix: can not submit in group form

### LINKED ISSUE #39: 1.3版本分组提交按钮点了没反应

### PR DESCRIPTION
**Pull request by ruibaby**
修复分组表单无法提交的问题。

/kind bug

Fixes #39 

可测试插件：[plugin-links-1.2.0-SNAPSHOT.jar.zip](https://github.com/halo-sigs/plugin-links/files/12227195/plugin-links-1.2.0-SNAPSHOT.jar.zip)

```release-note
修复分组表单无法提交的问题。
```

### CODE REVIEW

**Comment by ruibaby** [comment]
@chengzhongxue cc

**Comment by chengzhongxue** [comment]
@ruibaby 没问题

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by guqing — APPROVED** [review]
/approve

**Pull request merged**
